language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn test

before_deploy:
  - npm install -g auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: F5LlJWgWEbhSC93vy+NDJmvrMVUzpx+f911FdTmsPZB/muyKQgrBNDER8PDanOANNOdlNpPkDEDeGd99++7VBQDEGj5kJ9blKZAnGMK9KZ8CrNfBY8M1IWP+3is2zh0gYU2S91cqTX0o4qkEJz1ZQcC718IYROfSbTJFCHMF1u/Ut4vwA8iyMye0+VqEY5n+vucRCfKQXlAqxEh1ve3ektAA5MSNByWoUSWdKaghUlcf4iwLh8z28njLXEFYK6aQYnxvHzpDAMCJMK2YtsUMdI88p615l5N5aNmpmR+fwRVtwY2w37/IlC5OG6LpKj6o0vun2SMAZK7YJXFAWhsi4lukvJrqTuPbYBbsbD2dhJQehy8YtwI8wNTMt9IfZqyJNpVqB3ww7KDBLSP2rw/IiV5h/EfiYtlb8XiTPa1xoImMF3Oig9ALwVzbNGRKfQL9FaJMUYH3cO7CtbGshasAMCRqeuWNfdc+z0g0idrPHZTPJVTDt73/Qx1XdTKhvuZrzxFEm0mv7sj6+3UJp239HIU/s7OK06k450t/mlqdwx89TVAhXhRQxBHfUHk8ORzcPvQzmcw728R3F1abCpq6CbKYY9v/Vfof4KQvl4xWfVSPLmEx+uzxxtbB8yuLKyK1hGE5Tbpg20VT7KBh/nrHn8JhQ4yZIUtDB1i+xUj7OOE=
  on:
    tags: true
    repo: simplabs/asset-size-reporter
